version: "3.7"
services:
  prestashop:
    container_name: phpunit
    image: ${PHPUNIT_IMAGE}
    environment:
      - PS_DOMAIN=localhost
      - PS_ENABLE_SSL=0
      - PS_DEV_MODE=0
      - XDEBUG_MODE=coverage
      - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www/html/modules/ps_accounts

